SELECT [ID]
      ,[date]
      ,[Customer Name]
      ,[Customer Number]
      ,[Contract Number]
      ,[Tenant GUID]
      ,[Subscription GUID]
      ,[Service ID]
      ,[Service Name]
      ,[Service Type]
      ,[Item Name]
      ,[Resource Name]
      ,[Resource Part Code]
      ,[Date Used Start]
      ,[Date Used Stop]
      ,[Date Billed]
      ,[Usage Metric]
      ,[Unit Cost]
      ,[Total Cost]
      ,[Total Sales]
      ,[Unit Sell]
  FROM [dbo].[usageIngressAll]
  WHERE [date] >= '2026-05-01' AND [Service Name] NOT LIKE '%Azure%'
  order by [Customer Name], [Subscription GUID], [date]